project:
  type: website

website:
  title: " Christianpolito.xyz"
  navbar:
    right:
      - home.qmd
      - about.qmd
      - icon: github
        href: https://github.com/ChristianPolito
      - icon: twitter
        href: https://twitter.com

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    right:
    - text: "License"
      href: LICENSE.md
    - text: "Code of Conduct"
      href: CODE_OF_CONDUCT.md



format:
  html:
    theme: lux
    css: styles.css




